use crate::{
    alignment::{
        Alignment, AlignmentStates,
        phmm::{
            DomainPhmm, GlobalPhmm, LocalPhmm, PhmmNumber, SemiLocalPhmm,
            components::{EmissionParams, TransitionParams},
            indexing::{DpIndex, IndexRangeInner, PhmmIndexRange, PhmmIndexable, SeqIndex},
            modules::{DomainModule, SemiLocalModule},
            sampling::{
                DomainEnterInsertError, DomainExitInsertError, LayerSamplingError, ModuleSamplingError,
                ModuleSamplingErrorKind, ParamSamplingError, ParamTrapError, SampleFromStateError, SampleFromStateErrorKind,
                SampledSequence, SamplingError, SamplingLayerErrorKind, SemiLocalEnterCoreError,
            },
            state::{PhmmState, PhmmStateOrModule},
            traverse::{
                DomainVisitor, EndInsert, EndInsertExit, GlobalVisitor, LocalVisitor, ModuleLocation, SemiLocalVisitor,
            },
        },
    },
    data::ByteIndexMap,
    math::sample_one_weighted,
};
use rand::{
    Rng,
    distr::{Distribution, weighted::WeightedIndex},
};
use std::ops::{Range, RangeInclusive};

/// The maximum length of an insertion that can be generated by the
/// [`SampleVisitor`]. This is required to ensure that sampling eventually
/// terminates, but is unlikely to ever be noticed by a user except in
/// pathological cases.
const MAX_INS_LEN: usize = 1000;

/// A visitor that makes decisions non-deterministically by sampling from the
/// pHMM, weighting the choices based on the parameters in the pHMM.
pub struct SampleVisitor<'a, R> {
    /// The random number generator used to make selections.
    rng:               &'a mut R,
    /// The emitted sequence that has been accumulated so far.
    pub(crate) seq:    Vec<u8>,
    /// The alignment states representing the path taken through the pHMM.
    ///
    /// This is updated during transitions for `M`, `D`, and `I`, and during
    /// domain emissions for `S`.
    pub(crate) states: AlignmentStates,
    /// The number of times the current insert state (if in an insert state) has
    /// been transitioned into. This is 0 if not in an insert state.
    ins_len:           usize,
}

impl<'a, R> SampleVisitor<'a, R> {
    /// Creates a new [`SampleVisitor`] for probabilistically sampling a path
    /// and sequence from a pHMM.
    pub fn new(rng: &'a mut R) -> Self {
        Self {
            rng,
            seq: Vec::new(),
            states: AlignmentStates::new(),
            ins_len: 0,
        }
    }
}

impl<R> SampleVisitor<'_, R>
where
    R: Rng,
{
    fn choose_emission<T, const S: usize>(
        &mut self, layer: DpIndex, state: PhmmState, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>,
    ) -> Result<usize, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let params = params.as_array();
        let probs = params.map(PhmmNumber::to_prob::<f64>);

        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| match state {
            PhmmState::Match => SamplingError::Layer(LayerSamplingError {
                kind: SamplingLayerErrorKind::EmissionMatch(ParamSamplingError::new_emission(e, params, map)),
                layer,
            }),
            PhmmState::Delete => unreachable!("state must be either PhmmState::Match or PhmmState::Insert"),
            PhmmState::Insert => SamplingError::Layer(LayerSamplingError {
                kind: SamplingLayerErrorKind::EmissionInsert(ParamSamplingError::new_emission(e, params, map)),
                layer,
            }),
        })?;

        self.seq.push(map.to_byte(idx));

        Ok(idx)
    }

    fn choose_core_transition<T, const S: usize>(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>,
    ) -> Result<PhmmState, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        use PhmmState::*;

        let params = params.exiting_params(exiting);

        // Check for ParamTrapError
        if exiting == Insert
            && params[Match as usize] == T::INFINITY
            && params[Delete as usize] == T::INFINITY
            && params[Insert as usize] > T::ZERO
        {
            return Err(LayerSamplingError {
                kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                    kind: SampleFromStateErrorKind::State(ParamTrapError::new_state(params).into()),
                    exiting,
                }),
                layer,
            }
            .into());
        }

        let mut probs = params.map(PhmmNumber::to_prob::<f64>);

        // If needed, disallow transition into the INSERT state
        if self.ins_len == MAX_INS_LEN {
            probs[Insert as usize] = 0.0;
        }

        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| LayerSamplingError {
            kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                kind: SampleFromStateErrorKind::State(ParamSamplingError::new_state(e, params).into()),
                exiting,
            }),
            layer,
        })?;

        let state = PhmmState::VARIANTS[idx];

        // Update ins_len
        if state == PhmmState::Insert {
            self.ins_len += 1;
        } else {
            self.ins_len = 0;
        }

        let op = match state {
            PhmmState::Match => b'M',
            PhmmState::Delete => b'D',
            PhmmState::Insert => b'I',
        };
        self.states.add_state(op);

        Ok(state)
    }

    fn choose_end_or_insert<T, const S: usize>(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>,
    ) -> Result<EndInsert, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        use PhmmState::*;

        let end_param = params[(exiting, Match)];
        let insert_param = params[(exiting, Insert)];
        let params = [end_param, insert_param];

        // Check for ParamTrapError
        if exiting == Insert && end_param == T::INFINITY && insert_param > T::ZERO {
            return Err(LayerSamplingError {
                kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                    kind: SampleFromStateErrorKind::EndOrInsert(
                        ParamTrapError::new_end_or_insert(end_param, insert_param).into(),
                    ),
                    exiting,
                }),
                layer,
            }
            .into());
        }

        let mut probs = params.map(PhmmNumber::to_prob::<f64>);

        // If needed, disallow transition into the INSERT state
        if self.ins_len == MAX_INS_LEN {
            probs[1] = 0.0;
        }

        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Layer(LayerSamplingError {
                kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                    kind: SampleFromStateErrorKind::EndOrInsert(
                        ParamSamplingError::new_end_or_insert(e, end_param, insert_param).into(),
                    ),
                    exiting,
                }),
                layer,
            })
        })?;

        // Update ins_len and other state
        if idx == 0 {
            self.ins_len = 0;
            Ok(EndInsert::End)
        } else {
            self.ins_len += 1;
            self.states.add_state(b'I');
            Ok(EndInsert::Insert)
        }
    }

    fn choose_core_transition_or_exit<T, const S: usize>(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T,
    ) -> Result<PhmmStateOrModule, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let [into_match, into_delete, into_insert] = params.exiting_params(PhmmState::Match);
        let params = [into_match, into_delete, into_insert, exit_param];
        let probs = params.map(PhmmNumber::to_prob::<f64>);
        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Layer(LayerSamplingError {
                kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                    kind:    SampleFromStateErrorKind::StateOrExit(ParamSamplingError::new_state_or_exit(e, params)),
                    exiting: PhmmState::Match,
                }),
                layer,
            })
        })?;

        let state = PhmmStateOrModule::VARIANTS[idx];

        match state {
            PhmmStateOrModule::Match => self.states.add_state(b'M'),
            PhmmStateOrModule::Delete => self.states.add_state(b'D'),
            PhmmStateOrModule::Insert => {
                // We are transitioning from MATCH, so ins_len is currently 0
                self.ins_len = 1;
                self.states.add_state(b'I');
            }
            PhmmStateOrModule::Module => {}
        }

        Ok(state)
    }

    fn choose_end_insert_or_exit<T, const S: usize>(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T, _exit_from_end_param: T,
    ) -> Result<EndInsertExit, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let end_param = params[(PhmmState::Match, PhmmState::Match)];
        let insert_param = params[(PhmmState::Match, PhmmState::Insert)];

        let params = [end_param, insert_param, exit_param];
        let probs = params.map(PhmmNumber::to_prob::<f64>);
        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Layer(LayerSamplingError {
                kind: SamplingLayerErrorKind::FromState(SampleFromStateError {
                    kind:    SampleFromStateErrorKind::EndInsertOrExit(ParamSamplingError::new_end_insert_or_exit(
                        e,
                        end_param,
                        insert_param,
                        exit_param,
                    )),
                    exiting: PhmmState::Match,
                }),
                layer,
            })
        })?;

        match idx {
            0 => Ok(EndInsertExit::End),
            1 => {
                // We are transitioning from MATCH, so ins_len is currently 0
                self.ins_len = 1;
                self.states.add_state(b'I');
                Ok(EndInsertExit::Insert)
            }
            _ => Ok(EndInsertExit::Exit),
        }
    }

    fn enter_core<T, const S: usize>(&mut self, module: &SemiLocalModule<T>) -> Result<DpIndex, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let params = module.as_slice();
        let probs = params.iter().copied().map(PhmmNumber::to_prob::<f64>);
        let dist = WeightedIndex::new(probs).map_err(|e| {
            SamplingError::Module(ModuleSamplingError {
                kind: ModuleSamplingErrorKind::SemiLocalEnterCore(SemiLocalEnterCoreError {
                    params: module.as_slice().to_vec(),
                    source: e.into(),
                }),
                loc:  ModuleLocation::Begin,
            })
        })?;
        let idx = dist.sample(self.rng);

        // Only add match state if not entering BEGIN or END
        if (1..params.len() - 1).contains(&idx) {
            self.states.add_state(b'M');
        }

        Ok(DpIndex(idx))
    }

    fn choose_domain_emission<T, const S: usize>(
        &mut self, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>, loc: ModuleLocation,
    ) -> Result<usize, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let params = params.as_array();
        let probs = params.map(PhmmNumber::to_prob::<f64>);
        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Module(ModuleSamplingError {
                kind: ModuleSamplingErrorKind::DomainSampleEmissionsError(ParamSamplingError::new_emission(e, params, map)),
                loc,
            })
        })?;

        self.seq.push(map.to_byte(idx));
        self.states.add_state(b'S');

        Ok(idx)
    }

    fn enter_module_insert<T, const S: usize>(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation,
    ) -> Result<bool, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let params = [module.start_to_end, module.start_to_insert];
        let probs = params.map(PhmmNumber::to_prob::<f64>);
        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Module(ModuleSamplingError {
                kind: ModuleSamplingErrorKind::DomainEnterInsert(DomainEnterInsertError(
                    ParamSamplingError::new_end_or_insert(e, module.start_to_end, module.start_to_insert),
                )),
                loc,
            })
        })?;

        if idx == 0 {
            Ok(false)
        } else {
            self.ins_len = 1;
            Ok(true)
        }
    }

    fn exit_module_insert<T, const S: usize>(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation,
    ) -> Result<bool, SamplingError<T, S>>
    where
        T: PhmmNumber, {
        let params = [module.insert_to_end, module.insert_to_insert];

        // Check for ParamTrapError
        if module.insert_to_end == T::INFINITY && module.insert_to_insert > T::ZERO {
            return Err(ModuleSamplingError {
                kind: ModuleSamplingErrorKind::DomainExitInsert(DomainExitInsertError(
                    ParamTrapError::new_end_or_insert(module.insert_to_end, module.insert_to_insert).into(),
                )),
                loc,
            }
            .into());
        }

        let mut probs = params.map(PhmmNumber::to_prob::<f64>);

        // If needed, disallow transition into the INSERT state
        if self.ins_len == MAX_INS_LEN {
            probs[1] = 0.0;
        }

        let idx = sample_one_weighted(self.rng, &probs).map_err(|e| {
            SamplingError::Module(ModuleSamplingError {
                kind: ModuleSamplingErrorKind::DomainExitInsert(DomainExitInsertError(
                    ParamSamplingError::new_end_or_insert(e, module.insert_to_end, module.insert_to_insert).into(),
                )),
                loc,
            })
        })?;

        if idx == 0 {
            self.ins_len = 0;
            Ok(true)
        } else {
            self.ins_len += 1;
            Ok(false)
        }
    }
}

impl<R, T, const S: usize> GlobalVisitor<T, S> for SampleVisitor<'_, R>
where
    R: Rng,
    T: PhmmNumber,
{
    type Output = SampledSequence<()>;
    type Error = SamplingError<T, S>;

    fn choose_emission(
        &mut self, layer: DpIndex, state: PhmmState, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>,
        _phmm: &GlobalPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_emission(layer, state, params, map)
    }

    fn choose_core_transition(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &GlobalPhmm<T, S>,
    ) -> Result<PhmmState, SamplingError<T, S>> {
        self.choose_core_transition(layer, exiting, params)
    }

    fn choose_end_or_insert(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &GlobalPhmm<T, S>,
    ) -> Result<EndInsert, SamplingError<T, S>> {
        self.choose_end_or_insert(layer, exiting, params)
    }

    fn finalize(self, phmm: &GlobalPhmm<T, S>) -> Result<SampledSequence<()>, Self::Error> {
        let alignment = Alignment {
            score:       (),
            ref_range:   0..phmm.seq_len(),
            query_range: 0..self.seq.len(),
            states:      self.states,
            ref_len:     phmm.seq_len(),
            query_len:   self.seq.len(),
        };

        Ok(SampledSequence {
            sequence: self.seq,
            alignment,
        })
    }
}

impl<R, T, const S: usize> DomainVisitor<T, S> for SampleVisitor<'_, R>
where
    R: Rng,
    T: PhmmNumber,
{
    type Output = SampledSequence<()>;
    type Error = SamplingError<T, S>;

    fn choose_emission(
        &mut self, layer: DpIndex, state: PhmmState, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>,
        _phmm: &DomainPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_emission(layer, state, params, map)
    }

    fn choose_core_transition(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &DomainPhmm<T, S>,
    ) -> Result<PhmmState, SamplingError<T, S>> {
        self.choose_core_transition(layer, exiting, params)
    }

    fn choose_end_or_insert(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &DomainPhmm<T, S>,
    ) -> Result<EndInsert, SamplingError<T, S>> {
        self.choose_end_or_insert(layer, exiting, params)
    }

    fn choose_domain_emission(
        &mut self, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>, loc: ModuleLocation, _phmm: &DomainPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_domain_emission(params, map, loc)
    }

    fn enter_module_insert(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation, _phmm: &DomainPhmm<T, S>,
    ) -> Result<bool, SamplingError<T, S>> {
        self.enter_module_insert(module, loc)
    }

    fn exit_module_insert(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation, _phmm: &DomainPhmm<T, S>,
    ) -> Result<bool, SamplingError<T, S>> {
        self.exit_module_insert(module, loc)
    }

    fn exiting_module(
        &mut self, _module: &DomainModule<T, S>, _loc: ModuleLocation, _phmm: &DomainPhmm<T, S>,
    ) -> Result<(), Self::Error> {
        Ok(())
    }

    fn finalize(self, phmm: &DomainPhmm<T, S>, query_range: Range<SeqIndex>) -> Result<Self::Output, Self::Error> {
        let alignment = Alignment {
            score:       (),
            ref_range:   0..phmm.seq_len(),
            query_range: query_range.into_inner(),
            states:      self.states,
            ref_len:     phmm.seq_len(),
            query_len:   self.seq.len(),
        };

        Ok(SampledSequence {
            sequence: self.seq,
            alignment,
        })
    }
}

impl<R, T, const S: usize> SemiLocalVisitor<T, S> for SampleVisitor<'_, R>
where
    R: Rng,
    T: PhmmNumber,
{
    type Output = SampledSequence<()>;
    type Error = SamplingError<T, S>;

    fn choose_emission(
        &mut self, layer: DpIndex, state: PhmmState, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>,
        _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_emission(layer, state, params, map)
    }

    fn choose_core_transition(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<PhmmState, SamplingError<T, S>> {
        self.choose_core_transition(layer, exiting, params)
    }

    fn choose_end_or_insert(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<EndInsert, SamplingError<T, S>> {
        self.choose_end_or_insert(layer, exiting, params)
    }

    fn choose_core_transition_or_exit(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T, _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<PhmmStateOrModule, SamplingError<T, S>> {
        self.choose_core_transition_or_exit(layer, params, exit_param)
    }

    fn choose_end_insert_or_exit(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T, exit_from_end_param: T,
        _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<EndInsertExit, SamplingError<T, S>> {
        self.choose_end_insert_or_exit(layer, params, exit_param, exit_from_end_param)
    }

    fn enter_core(
        &mut self, module: &SemiLocalModule<T>, _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<DpIndex, SamplingError<T, S>> {
        self.enter_core(module)
    }

    fn exit_core_from_end(
        &mut self, _layer: DpIndex, _exit_param: T, _phmm: &SemiLocalPhmm<T, S>,
    ) -> Result<(), SamplingError<T, S>> {
        Ok(())
    }

    fn exit_core(&mut self, _layer_idx: DpIndex, _exit_param: T, _phmm: &SemiLocalPhmm<T, S>) -> Result<(), Self::Error> {
        Ok(())
    }

    fn finalize(
        self, phmm: &SemiLocalPhmm<T, S>, aligned_layers: RangeInclusive<DpIndex>,
    ) -> Result<Self::Output, Self::Error> {
        let alignment = Alignment {
            score:       (),
            ref_range:   aligned_layers.saturating_to_seq_range(&phmm).into_inner(),
            query_range: 0..self.seq.len(),
            states:      self.states,
            ref_len:     phmm.seq_len(),
            query_len:   self.seq.len(),
        };

        Ok(SampledSequence {
            sequence: self.seq,
            alignment,
        })
    }
}

impl<R, T, const S: usize> LocalVisitor<T, S> for SampleVisitor<'_, R>
where
    R: Rng,
    T: PhmmNumber,
{
    type Output = SampledSequence<()>;
    type Error = SamplingError<T, S>;

    fn choose_emission(
        &mut self, layer: DpIndex, state: PhmmState, params: &EmissionParams<T, S>, map: &ByteIndexMap<S>,
        _phmm: &LocalPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_emission(layer, state, params, map)
    }

    fn choose_core_transition(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &LocalPhmm<T, S>,
    ) -> Result<PhmmState, SamplingError<T, S>> {
        self.choose_core_transition(layer, exiting, params)
    }

    fn choose_end_or_insert(
        &mut self, layer: DpIndex, exiting: PhmmState, params: &TransitionParams<T>, _phmm: &LocalPhmm<T, S>,
    ) -> Result<EndInsert, SamplingError<T, S>> {
        self.choose_end_or_insert(layer, exiting, params)
    }

    fn choose_core_transition_or_exit(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T, _phmm: &LocalPhmm<T, S>,
    ) -> Result<PhmmStateOrModule, SamplingError<T, S>> {
        self.choose_core_transition_or_exit(layer, params, exit_param)
    }

    fn choose_end_insert_or_exit(
        &mut self, layer: DpIndex, params: &TransitionParams<T>, exit_param: T, exit_from_end_param: T,
        _phmm: &LocalPhmm<T, S>,
    ) -> Result<EndInsertExit, SamplingError<T, S>> {
        self.choose_end_insert_or_exit(layer, params, exit_param, exit_from_end_param)
    }

    fn enter_core(&mut self, module: &SemiLocalModule<T>, _phmm: &LocalPhmm<T, S>) -> Result<DpIndex, SamplingError<T, S>> {
        self.enter_core(module)
    }

    fn exit_core_from_end(
        &mut self, _layer: DpIndex, _exit_param: T, _phmm: &LocalPhmm<T, S>,
    ) -> Result<(), SamplingError<T, S>> {
        Ok(())
    }

    fn choose_local_emission(
        &mut self, params: &EmissionParams<T, S>, mapping: &ByteIndexMap<S>, loc: ModuleLocation, _phmm: &LocalPhmm<T, S>,
    ) -> Result<usize, SamplingError<T, S>> {
        self.choose_domain_emission(params, mapping, loc)
    }

    fn enter_module_insert(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation, _phmm: &LocalPhmm<T, S>,
    ) -> Result<bool, SamplingError<T, S>> {
        self.enter_module_insert(module, loc)
    }

    fn exit_module_insert(
        &mut self, module: &DomainModule<T, S>, loc: ModuleLocation, _phmm: &LocalPhmm<T, S>,
    ) -> Result<bool, SamplingError<T, S>> {
        self.exit_module_insert(module, loc)
    }

    fn exiting_domain_module(
        &mut self, _module: &DomainModule<T, S>, _loc: ModuleLocation, _phmm: &LocalPhmm<T, S>,
    ) -> Result<(), Self::Error> {
        Ok(())
    }

    fn exit_core(&mut self, _layer_idx: DpIndex, _exit_param: T, _phmm: &LocalPhmm<T, S>) -> Result<(), Self::Error> {
        Ok(())
    }

    fn finalize(
        self, phmm: &LocalPhmm<T, S>, aligned_layers: RangeInclusive<DpIndex>, query_range: Range<SeqIndex>,
    ) -> Result<Self::Output, Self::Error> {
        let alignment = Alignment {
            score:       (),
            ref_range:   aligned_layers.saturating_to_seq_range(&phmm).into_inner(),
            query_range: query_range.into_inner(),
            states:      self.states,
            ref_len:     phmm.seq_len(),
            query_len:   self.seq.len(),
        };

        Ok(SampledSequence {
            sequence: self.seq,
            alignment,
        })
    }
}
