//! Specification structs for generating arbitrary bytes (`u8` values).

use crate::data::arbitrary::ArbitrarySpecs;
use arbitrary::{Result, Unstructured};
use std::borrow::Cow;

/// Specifications for generating an arbitrary `u8` byte.
#[derive(Clone, Eq, PartialEq, Hash, Debug, Default)]
pub struct ByteSpecs {
    /// The character set to which the `u8` byte must belong.
    pub set: ByteSet,

    /// The case of the ASCII characters.
    pub case: Case,
}

impl<'a> ArbitrarySpecs<'a> for ByteSpecs {
    type Output = u8;

    #[inline]
    fn make_arbitrary(&self, u: &mut Unstructured<'a>) -> Result<Self::Output> {
        let byte = self.set.make_arbitrary(u)?;

        let cased = match self.case {
            Case::Lowercase => byte.to_ascii_lowercase(),
            Case::Uppercase => byte.to_ascii_uppercase(),
            Case::Any => byte,
        };

        Ok(cased)
    }
}

/// A view of [`ByteSpecs`], for use in avoiding cloning a custom byte set.
pub(crate) struct ByteSpecsView<'a> {
    pub set:  &'a ByteSet,
    pub case: Case,
}

impl Default for ByteSpecsView<'_> {
    fn default() -> Self {
        Self {
            set:  &ByteSet::Any,
            case: Case::Any,
        }
    }
}

impl<'a> ArbitrarySpecs<'a> for ByteSpecsView<'_> {
    type Output = u8;

    #[inline]
    fn make_arbitrary(&self, u: &mut Unstructured<'a>) -> Result<Self::Output> {
        let byte = self.set.make_arbitrary(u)?;

        let cased = match self.case {
            Case::Lowercase => byte.to_ascii_lowercase(),
            Case::Uppercase => byte.to_ascii_uppercase(),
            Case::Any => byte,
        };

        Ok(cased)
    }
}

/// The desired case of the ASCII generated byte(s).
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug, Default)]
pub enum Case {
    /// Converts all ASCII letters to lowercase.
    Lowercase,

    /// Converts all ASCII letters to uppercase.
    Uppercase,

    /// Imposes no restrictions on the case of the generated byte(s).
    #[default]
    Any,
}

/// The character set of the generated byte(s).
#[derive(Clone, Eq, PartialEq, Hash, Debug, Default)]
pub enum ByteSet {
    /// Includes any `u8` value.
    #[default]
    Any,

    /// Includes only ASCII values (range `0..=127`).
    Ascii,

    /// Includes only graphic ASCII values or spaces (range `32..=126`).
    AsciiGraphicOrSpace,

    /// Includes only graphic ASCII values (range `33..=126`).
    AsciiGraphic,

    /// Includes only graphic ASCII that is not a special character in bash.
    ///
    /// This includes the characters
    /// `%+,-./0123456789:@ABCDEFGHIJKLMNOPQRSTUVWXYZ^_abcdefghijklmnopqrstuvwxyz`.
    AsciiGraphicBashSafe,

    /// Includes the canonical DNA bases `ACGT` in both cases, with additional
    /// options configured by [`NucleotidesByteSet`].
    NucleotidesCanonical(NucleotidesByteSet),

    /// Includes the IUPAC DNA bases `ACGTURYSWKMBDHV` in both cases, with
    /// additional options configured by [`NucleotidesByteSet`].
    NucleotidesIupac(NucleotidesByteSet),

    /// Includes the 20 canonical amino acids `ACDEFGHIKLMNPQRSTVWY` in both
    /// cases, with additional options configured by [`AminoAcidsByteSet`].
    AminoAcidsCanonical(AminoAcidsByteSet),

    /// Includes a custom set of bytes.
    Custom(Cow<'static, [u8]>),
}

/// Specifications for what special characters should be included when
/// generating arbitrary nucleotide bases.
///
/// All options are opt-out. By default, `N` and `U` and `-` will be included.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub struct NucleotidesByteSet {
    /// Whether to include `N` in both cases.
    pub include_n: bool,

    /// Whether to include `U` in both cases.
    pub include_u: bool,

    /// Whether to include the `-` gap character.
    pub with_gaps: bool,
}

impl Default for NucleotidesByteSet {
    #[inline]
    fn default() -> Self {
        Self {
            include_n: true,
            include_u: true,
            with_gaps: true,
        }
    }
}

impl NucleotidesByteSet {
    /// Given the base characters to generate, returns a vector containing all
    /// the allowable bytes that may be chosen.
    ///
    /// ## Validity
    ///
    /// `base_chars` should not contain any of `NnUu-`.
    #[inline]
    #[must_use]
    pub fn generate_alphabet(self, base_chars: &[u8]) -> Vec<u8> {
        let mut chars = base_chars.to_vec();
        if self.include_n {
            chars.extend_from_slice(b"Nn");
        }
        if self.include_u {
            chars.extend_from_slice(b"Uu");
        }
        if self.with_gaps {
            chars.push(b'-');
        }
        chars
    }

    /// Returns whether `byte` is contained in either the `base_chars` or the
    /// additional characters as specified in [`NucleotidesByteSet`].
    #[must_use]
    pub fn contains(self, byte: u8, base_chars: &[u8]) -> bool {
        (self.include_n && byte.eq_ignore_ascii_case(&b'N'))
            || (self.include_u && byte.eq_ignore_ascii_case(&b'U'))
            || (self.with_gaps && byte == b'-')
            || base_chars.contains(&byte)
    }
}

/// Specifications for what special characters should be included when
/// generating arbitrary amino acids.
///
/// All options are opt-out. By default, `X` and `-` will be included.
#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub struct AminoAcidsByteSet {
    /// Whether to include `X` in both cases.
    pub include_x: bool,

    /// Whether to include the `-` gap character.
    pub with_gaps: bool,
}

impl Default for AminoAcidsByteSet {
    fn default() -> Self {
        Self {
            include_x: true,
            with_gaps: true,
        }
    }
}

impl AminoAcidsByteSet {
    /// Given the base characters to generate, returns a vector containing all
    /// the allowable bytes that may be chosen.
    ///
    /// ## Validity
    ///
    /// `base_chars` should not contain any of `Xx-`.
    #[inline]
    #[must_use]
    pub fn generate_alphabet(self, base_chars: &[u8]) -> Vec<u8> {
        let mut chars = base_chars.to_vec();
        if self.include_x {
            chars.extend_from_slice(b"Xx");
        }
        if self.with_gaps {
            chars.push(b'-');
        }
        chars
    }

    /// Returns whether `byte` is contained in either the `base_chars` or the
    /// additional characters as specified in [`AminoAcidsByteSet`].
    #[must_use]
    pub fn contains(self, byte: u8, base_chars: &[u8]) -> bool {
        (self.include_x && byte.eq_ignore_ascii_case(&b'X'))
            || (self.with_gaps && byte == b'-')
            || base_chars.contains(&byte)
    }
}

impl<'a> ArbitrarySpecs<'a> for ByteSet {
    type Output = u8;

    #[inline]
    fn make_arbitrary(&self, u: &mut Unstructured<'a>) -> Result<Self::Output> {
        match self {
            ByteSet::Any => u.arbitrary(),
            ByteSet::Ascii => u.int_in_range(0..=127),
            ByteSet::AsciiGraphicOrSpace => u.int_in_range(b' '..=b'~'),
            ByteSet::AsciiGraphic => u.int_in_range(b'!'..=b'~'),
            ByteSet::AsciiGraphicBashSafe => u
                .choose(b"%+,-./0123456789:@ABCDEFGHIJKLMNOPQRSTUVWXYZ^_abcdefghijklmnopqrstuvwxyz")
                .copied(),
            ByteSet::NucleotidesCanonical(set) => {
                let chars = set.generate_alphabet(b"ACGTacgt");
                u.choose(&chars).copied()
            }
            ByteSet::NucleotidesIupac(set) => {
                let chars = set.generate_alphabet(b"ACGTRYSWKMBDHVacgtryswkmbdhv");
                u.choose(&chars).copied()
            }
            ByteSet::AminoAcidsCanonical(set) => {
                let chars = set.generate_alphabet(b"ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwy");
                u.choose(&chars).copied()
            }
            ByteSet::Custom(items) => u.choose(items).copied(),
        }
    }
}

impl<T> From<T> for ByteSet
where
    Cow<'static, [u8]>: From<T>,
{
    fn from(value: T) -> Self {
        ByteSet::Custom(Cow::from(value))
    }
}

impl ByteSet {
    /// Retrieves a vector with the allowable bytes that may be chosen.
    #[must_use]
    pub fn generate_alphabet(&self) -> Vec<u8> {
        match self {
            ByteSet::Any => (0..=u8::MAX).collect(),
            ByteSet::Ascii => (0..=127).collect(),
            ByteSet::AsciiGraphicOrSpace => (b' '..=b'~').collect(),
            ByteSet::AsciiGraphic => (b'!'..=b'~').collect(),
            ByteSet::AsciiGraphicBashSafe => {
                b"%+,-./0123456789:@ABCDEFGHIJKLMNOPQRSTUVWXYZ^_abcdefghijklmnopqrstuvwxyz".to_vec()
            }
            ByteSet::NucleotidesCanonical(set) => set.generate_alphabet(b"ACGTacgt"),
            ByteSet::NucleotidesIupac(set) => set.generate_alphabet(b"ACGTURYSWKMBDHVacgturyswkmbdhv"),
            ByteSet::AminoAcidsCanonical(set) => set.generate_alphabet(b"ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwy"),
            ByteSet::Custom(cow) => cow.to_vec(),
        }
    }

    /// Consumes the given [`ByteSet`], returning a vector with the allowable
    /// bytes that may be chosen.
    ///
    /// This avoids a clone if an owned [`Custom`] variant is used.
    fn into_alphabet(self) -> Vec<u8> {
        match self {
            ByteSet::Custom(cow) => cow.into_owned(),
            other => other.generate_alphabet(),
        }
    }

    /// Returns whether the [`ByteSet`] contains a given byte.
    #[must_use]
    pub fn contains(&self, byte: u8) -> bool {
        match self {
            ByteSet::Any => true,
            ByteSet::Ascii => (0..=127).contains(&byte),
            ByteSet::AsciiGraphicOrSpace => (b' '..=b'~').contains(&byte),
            ByteSet::AsciiGraphic => (b'!'..=b'~').contains(&byte),
            ByteSet::AsciiGraphicBashSafe => {
                b"%+,-./0123456789:@ABCDEFGHIJKLMNOPQRSTUVWXYZ^_abcdefghijklmnopqrstuvwxyz".contains(&byte)
            }
            ByteSet::NucleotidesCanonical(set) => set.contains(byte, b"ACGTacgt"),
            ByteSet::NucleotidesIupac(set) => set.contains(byte, b"ACGTURYSWKMBDHVacgturyswkmbdhv"),
            ByteSet::AminoAcidsCanonical(set) => set.contains(byte, b"ACDEFGHIKLMNPQRSTVWYacdefghiklmnpqrstvwy"),
            ByteSet::Custom(set) => set.contains(&byte),
        }
    }

    /// Removes a given byte from the [`ByteSet`].
    ///
    /// ## Limitations
    ///
    /// This may cause an allocation and the [`Custom`] variant to be used.
    ///
    /// [`Custom`]: ByteSet::Custom
    pub fn remove(&mut self, byte: u8) {
        if !self.contains(byte) {
            return;
        }

        let old_set = std::mem::take(self);
        let alphabet = old_set.into_alphabet().into_iter().filter(|x| *x != byte).collect::<Vec<_>>();
        let new_set = ByteSet::from(alphabet);
        *self = new_set;
    }
}
