name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - test

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract Changelog
        id: extract_changelog
        shell: bash
        run: perl .github/scripts/last_release_notes.pl > $RUNNER_TEMP/release_notes.md

      - name: Create Release
        id: create_release
        shell: bash
        run: |
          [[ "${{ github.ref_name }}" == "test" ]] && latest="--latest=false" || latest=

          gh release create "${{ github.ref_name }}" \
          --title "Zoe ${{ github.ref_name }}" \
          --notes-file "$RUNNER_TEMP/release_notes.md" \
          $latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
